export default {
  GET_WEATHER_ONE_START: "weather/GET_WEATHER_ONE_START",
  GET_WEATHER_ONE_SECCESS: "weather/GET_WEATHER_ONE_SECCESS",
  GET_WEATHER_ONE_FAILURE: "weather/GET_WEATHER_ONE_FAILURE",

  GET_WEATHER_FIVE_START: "weather/GET_WEATHER_FIVE_START",
  GET_WEATHER_FIVE_SECCESS: "weather/GET_WEATHER_FIVE_SECCESS",
  GET_WEATHER_FIVE_FAILURE: "weather/GET_WEATHER_FIVE_FAILURE"
};
// const GET_WEATHER_ONE_START = "weather/GET_WEATHER_ONE_START";
// const GET_WEATHER_ONE_SECCESS = "weather/GET_WEATHER_ONE_SECCESS";
// const GET_WEATHER_ONE_FAILURE = "weather/GET_WEATHER_ONE_FAILURE";

// const GET_WEATHER_FIVE_START = "weather/GET_WEATHER_FIVE_START";
// const GET_WEATHER_FIVE_SECCESS = "weather/GET_WEATHER_FIVE_SECCESS";
// const GET_WEATHER_FIVE_FAILURE = "weather/GET_WEATHER_FIVE_FAILURE";
